# docker-compose example for tenderduty, copy this file to docker-compose.yml and edit to suit.
version: '3.9'

networks:
  monitor-net:
    driver: bridge

volumes:
  home:
  ssl-conf:

services:
  tenderduty:
    image: ghcr.io/blockpane/tenderduty:latest
    command: ""
    ports:
      - "8888:8888"   # Dashboard
      - "28686:28686"  # Prometheus exporter
    volumes:
      - home:/var/lib/tenderduty
      - ./config.yml:/var/lib/tenderduty/config.yml
      - ./chains.d:/var/lib/tenderduty/chains.d/
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: unless-stopped
    networks:
      - monitor-net
    container_name: tenderduty
  
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./ssl-conf/nginx:/etc/nginx/conf.d
      - ./ssl-conf/certbot/conf:/etc/letsencrypt
      - ./ssl-conf/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - tenderduty
    networks:
      - monitor-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./ssl-conf/certbot/conf:/etc/letsencrypt
      - ./ssl-conf/certbot/www:/var/www/certbot
    depends_on:
      - tenderduty
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
